name: docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install latex
      run: sudo apt install -y latexmk texlive-latex-extra texlive-science texlive-lang-portuguese

    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    
    - name: Give permission to execute
      run: chmod u+x *.sh

    - name: Compile test1
      run: make tests/test1/AEDA-T1-teor.pdf
    - name: Upload test1
      uses: actions/upload-artifact@v2
      with:
        name: AEDA-T1-teor.pdf
        path: tests/test1/AEDA-T1-teor.pdf

    - name: Compile test2
      run: make tests/test2/AEDA-T2-teor.pdf
    - name: Upload test2
      uses: actions/upload-artifact@v2
      with:
        name: AEDA-T2-teor.pdf
        path: tests/test2/AEDA-T2-teor.pdf

    - name: Compile test3
      run: make tests/test3/AEDA-T3-teor.pdf
    - name: Upload test3
      uses: actions/upload-artifact@v2
      with:
        name: AEDA-T3-teor.pdf
        path: tests/test3/AEDA-T3-teor.pdf
