name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: test tp01
      run: |
        cd tp/tp01/aeda1920_fp01
        mkdir build && cd build
        cmake .. && make
        ./aeda1920_fp01

    - name: test tp02
      run: |
        cd tp/tp02/aeda1920_fp02
        mkdir build && cd build
        cmake .. && make
        ./aeda1920_fp02

    - name: test tp03
      run: |
        cd tp/tp03/aeda1920_fp03
        mkdir build && cd build
        cmake .. && make
        ./aeda1920_fp03

    - name: test tp04
      run: |
        cd tp/tp04/aeda1920_fp04
        mkdir build && cd build
        cmake .. && make
        ./aeda1920_fp04

    - name: test tp05
      run: |
        cd tp/tp05/aeda1920_fp05
        mkdir build && cd build
        cmake .. && make
        ./aeda1920_fp05

