name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  submodules:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

  test-tp01:
    runs-on: ubuntu-latest
    needs: submodules
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd tp/tp01/aeda1920_fp01
        mkdir build && cd build
        cmake .. && make
    - name: test
      run: cd tp/tp01/aeda1920_fp01/build && ./aeda1920_fp01

  test-tp02:
    runs-on: ubuntu-latest
    needs: submodules
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd tp/tp02/aeda1920_fp02
        mkdir build && cd build
        cmake .. && make
    - name: test
      run: cd tp/tp02/aeda1920_fp02/build && ./aeda1920_fp02

  test-tp03:
    runs-on: ubuntu-latest
    needs: submodules
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd tp/tp03/aeda1920_fp03
        mkdir build && cd build
        cmake .. && make
    - name: test
      run: cd tp/tp03/aeda1920_fp03/build && ./aeda1920_fp03

  test-tp04:
    runs-on: ubuntu-latest
    needs: submodules
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd tp/tp04/aeda1920_fp04
        mkdir build && cd build
        cmake .. && make
    - name: test
      run: cd tp/tp04/aeda1920_fp04/build && ./aeda1920_fp04

  test-tp05:
    runs-on: ubuntu-latest
    needs: submodules
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd tp/tp05/aeda1920_fp05
        mkdir build && cd build
        cmake .. && make
    - name: test
      run: cd tp/tp05/aeda1920_fp05/build && ./aeda1920_fp05

  test-tp06:
    runs-on: ubuntu-latest
    needs: submodules
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd tp/tp06/aeda1920_fp06
        mkdir build && cd build
        cmake .. && make
    - name: test
      run: cd tp/tp06/aeda1920_fp06/build && ./aeda1920_fp06

  test-tp07:
    runs-on: ubuntu-latest
    needs: submodules
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd tp/tp07/aeda1920_fp07
        mkdir build && cd build
        cmake .. && make
    - name: test
      run: cd tp/tp07/aeda1920_fp07/build && ./aeda1920_fp07

  test-tp09:
    runs-on: ubuntu-latest
    needs: submodules
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd tp/tp09/aeda1920_fp09
        mkdir build && cd build
        cmake .. && make
    - name: test
      run: cd tp/tp09/aeda1920_fp09/build && ./aeda1920_fp09

  test-tp10:
    runs-on: ubuntu-latest
    needs: submodules
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd tp/tp10/aeda1920_fp10
        mkdir build && cd build
        cmake .. && make
    - name: test
      run: cd tp/tp10/aeda1920_fp10/build && ./aeda1920_fp10

  test-tp11:
    runs-on: ubuntu-latest
    needs: submodules
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd tp/tp11/aeda1920_fp11
        mkdir build && cd build
        cmake .. && make
    - name: test
      run: cd tp/tp11/aeda1920_fp11/build && ./aeda1920_fp11

  test-2018t1:
    runs-on: ubuntu-latest
    needs: submodules
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd tests/test1/2018/aeda1819_ci1_googleTest
        mkdir build && cd build
        cmake .. && make
    - name: test
      run: cd tests/test1/2018/aeda1819_ci1_googleTest/build && ./aeda1819_ci1

  test-2017t1:
    runs-on: ubuntu-latest
    needs: submodules
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd tests/test1/2017/aeda1718_ci1
        mkdir build && cd build
        g++ -Wall ../Test.cpp ../Car.cpp -o aeda1718_ci1
    - name: test
      run: cd tests/test1/2017/aeda1718_ci1/build && ./aeda1718_ci1

  test-2016t1:
    runs-on: ubuntu-latest
    needs: submodules
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd tests/test1/2016/2016_ficheiros
        mkdir build && cd build
        g++ -Wall ../Mail.cpp ../Postman.cpp ../PostOffice.cpp ../Test.cpp -o aeda1617_ci1
    - name: test
      run: cd tests/test1/2016/2016_ficheiros/build && ./aeda1617_ci1

  test-2018t2:
    runs-on: ubuntu-latest
    needs: submodules
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd tests/test2/2018/aeda1819_ci2_googleTest
        mkdir build && cd build
        cmake .. && make
    - name: test
      run: cd tests/test2/2018/aeda1819_ci2_googleTest/build && ./aeda1819_ci2

  test-2017t2:
    runs-on: ubuntu-latest
    needs: submodules
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd tests/test2/2017/aeda1718_ci2
        mkdir build && cd build
        g++ -Wall -I../CUTE/cute ../Doctor.cpp ../Hospital.cpp ../Test.cpp -o aeda1718_ci2
    - name: test
      run: cd tests/test2/2017/aeda1718_ci2/build && ./aeda1718_ci2

  test-2018t3:
    runs-on: ubuntu-latest
    needs: submodules
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd tests/test3/2018/aeda1819_ci3_googleTest
        mkdir build && cd build
        cmake .. && make
    - name: test
      run: cd tests/test3/2018/aeda1819_ci3_googleTest/build && ./aeda1819_ci3
